"""
Módulo de Aplicação de Ativos e Scanners.
GovSec Shield — Application Layer (M3.4)
"""

from src.asset.application.asset_service import AssetManagementService
from src.asset.application.dto import (
    AssetGroupCreateDTO,
    AssetGroupPatchDTO,
    AssetGroupResponseDTO,
    AssetPatchDTO,
    AssetResponseDTO,
    ExecutionDispatchResponseDTO,
    MonitoringIntegrationCreateDTO,
    MonitoringIntegrationPatchDTO,
    MonitoringIntegrationResponseDTO,
    MonitoringTestResponseDTO,
    PaginatedResponse,
    ScanExecutionCreateDTO,
    ScanExecutionResponseDTO,
    ScannerProfileCreateDTO,
    ScannerProfilePatchDTO,
    ScannerProfileResponseDTO,
    ScanScheduleCreateDTO,
    ScanSchedulePatchDTO,
    ScanScheduleResponseDTO,
    ScanTargetCreateDTO,
    ScanTargetPatchDTO,
    ScanTargetResponseDTO,
    ServiceResponseDTO,
    TargetValidateRequestDTO,
    TargetValidationResponseDTO,
    VulnerabilityHistoryResponseDTO,
    VulnerabilityResponseDTO,
    VulnerabilityTriagePatchDTO,
)

__all__ = [
    "AssetManagementService",
    "PaginatedResponse",
    "AssetGroupCreateDTO",
    "AssetGroupPatchDTO",
    "AssetGroupResponseDTO",
    "ScanTargetCreateDTO",
    "ScanTargetPatchDTO",
    "ScanTargetResponseDTO",
    "TargetValidateRequestDTO",
    "TargetValidationResponseDTO",
    "AssetPatchDTO",
    "AssetResponseDTO",
    "ServiceResponseDTO",
    "ScannerProfileCreateDTO",
    "ScannerProfilePatchDTO",
    "ScannerProfileResponseDTO",
    "ScanScheduleCreateDTO",
    "ScanSchedulePatchDTO",
    "ScanScheduleResponseDTO",
    "ScanExecutionCreateDTO",
    "ExecutionDispatchResponseDTO",
    "ScanExecutionResponseDTO",
    "VulnerabilityTriagePatchDTO",
    "VulnerabilityResponseDTO",
    "VulnerabilityHistoryResponseDTO",
    "MonitoringIntegrationCreateDTO",
    "MonitoringIntegrationPatchDTO",
    "MonitoringIntegrationResponseDTO",
    "MonitoringTestResponseDTO",
]
